CASE_STATUS_DRAFT = "DRAFT"
CASE_STATUS_IN_REVIEW = "IN_REVIEW"
CASE_STATUS_ACTIVE = "ACTIVE"
CASE_STATUS_REVISION = "REVISION"
CASE_STATUS_ARCHIVED = "ARCHIVED"

ALLOWED_CASE_STATUS_TRANSITIONS = {
    CASE_STATUS_DRAFT: {
        CASE_STATUS_IN_REVIEW,
    },
    CASE_STATUS_IN_REVIEW: {
        CASE_STATUS_ACTIVE,
        CASE_STATUS_REVISION,
    },
    CASE_STATUS_REVISION: {
        CASE_STATUS_IN_REVIEW,
    },
    CASE_STATUS_ACTIVE: {
        CASE_STATUS_ARCHIVED,
    },
    CASE_STATUS_ARCHIVED: set(),
}
