"""fix: changed some fields after fixing ERD

Revision ID: 097f53865517
Revises: 
Create Date: 2026-04-09 14:02:09.236955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097f53865517'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_difficulty_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_code', sa.String(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('case_semesters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('difficulty_level_id', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('project_goals', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('required_result', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('grade_criteria', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('study_program', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cases', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'cases', ['id'])
    op.drop_constraint(op.f('cases_semester_id_fkey'), 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'case_difficulty_levels', ['difficulty_level_id'], ['id'])
    op.drop_column('cases', 'semester_id')
    op.drop_column('cases', 'description')
    op.add_column('grades', sa.Column('team_case_history_id', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'grades', ['id'])
    op.drop_constraint(op.f('grades_semester_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_case_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_team_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'team_case_history', ['team_case_history_id'], ['id'])
    op.drop_column('grades', 'semester_id')
    op.drop_column('grades', 'case_id')
    op.drop_column('grades', 'team_id')
    op.add_column('meetings', sa.Column('team_case_history_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('meetings_case_id_fkey'), 'meetings', type_='foreignkey')
    op.drop_constraint(op.f('meetings_team_id_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'team_case_history', ['team_case_history_id'], ['id'])
    op.drop_column('meetings', 'case_id')
    op.drop_column('meetings', 'team_id')
    op.add_column('students', sa.Column('university_id', sa.Integer(), nullable=False))
    op.alter_column('students', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'students', ['id'])
    op.create_foreign_key(None, 'students', 'university_info', ['university_id'], ['id'])
    op.add_column('team_case_history', sa.Column('case_semesters_id', sa.String(length=36), nullable=False))
    op.drop_index(op.f('ix_team_case_history_case_id'), table_name='team_case_history')
    op.drop_index(op.f('ix_team_case_history_semester_id'), table_name='team_case_history')
    op.create_unique_constraint(None, 'team_case_history', ['id'])
    op.drop_constraint(op.f('team_case_history_semester_id_fkey'), 'team_case_history', type_='foreignkey')
    op.drop_constraint(op.f('team_case_history_case_id_fkey'), 'team_case_history', type_='foreignkey')
    op.create_foreign_key(None, 'team_case_history', 'case_semesters', ['case_semesters_id'], ['id'])
    op.drop_column('team_case_history', 'semester_id')
    op.drop_column('team_case_history', 'case_id')
    op.create_unique_constraint(None, 'teams', ['id'])
    op.drop_constraint(op.f('teams_semester_id_fkey'), 'teams', type_='foreignkey')
    op.drop_constraint(op.f('teams_case_id_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'semester_id')
    op.drop_column('teams', 'case_id')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('teams', sa.Column('case_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('teams_case_id_fkey'), 'teams', 'cases', ['case_id'], ['id'])
    op.create_foreign_key(op.f('teams_semester_id_fkey'), 'teams', 'semesters', ['semester_id'], ['id'])
    op.drop_constraint(None, 'teams', type_='unique')
    op.add_column('team_case_history', sa.Column('case_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('team_case_history', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_case_history', type_='foreignkey')
    op.create_foreign_key(op.f('team_case_history_case_id_fkey'), 'team_case_history', 'cases', ['case_id'], ['id'])
    op.create_foreign_key(op.f('team_case_history_semester_id_fkey'), 'team_case_history', 'semesters', ['semester_id'], ['id'])
    op.drop_constraint(None, 'team_case_history', type_='unique')
    op.create_index(op.f('ix_team_case_history_semester_id'), 'team_case_history', ['semester_id'], unique=False)
    op.create_index(op.f('ix_team_case_history_case_id'), 'team_case_history', ['case_id'], unique=False)
    op.drop_column('team_case_history', 'case_semesters_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('students', 'university_id')
    op.add_column('meetings', sa.Column('team_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('case_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_team_id_fkey'), 'meetings', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('meetings_case_id_fkey'), 'meetings', 'cases', ['case_id'], ['id'])
    op.drop_column('meetings', 'team_case_history_id')
    op.add_column('grades', sa.Column('team_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('grades', sa.Column('case_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('grades', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_team_id_fkey'), 'grades', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('grades_case_id_fkey'), 'grades', 'cases', ['case_id'], ['id'])
    op.create_foreign_key(op.f('grades_semester_id_fkey'), 'grades', 'semesters', ['semester_id'], ['id'])
    op.drop_constraint(None, 'grades', type_='unique')
    op.drop_column('grades', 'team_case_history_id')
    op.add_column('cases', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key(op.f('cases_semester_id_fkey'), 'cases', 'semesters', ['semester_id'], ['id'])
    op.drop_constraint(None, 'cases', type_='unique')
    op.drop_column('cases', 'end_date')
    op.drop_column('cases', 'start_date')
    op.drop_column('cases', 'study_program')
    op.drop_column('cases', 'grade_criteria')
    op.drop_column('cases', 'required_result')
    op.drop_column('cases', 'project_goals')
    op.drop_column('cases', 'difficulty_level_id')
    op.drop_table('case_semesters')
    op.drop_table('case_difficulty_levels')
    # ### end Alembic commands ###
