"""feat: add uq between case_id and semester_id in CaseSemesters model

Revision ID: 0b26b543f638
Revises: 90551a1306a3
Create Date: 2026-05-09 18:58:34.072019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b26b543f638'
down_revision: Union[str, Sequence[str], None] = '90551a1306a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_case_id_semester_id', 'case_semesters', ['case_id', 'semester_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_case_id_semester_id', 'case_semesters', type_='unique')
    # ### end Alembic commands ###
