"""feat: add some new fields to meetings model

Revision ID: 897e5e96286d
Revises: 7a1c4d3e9b20
Create Date: 2026-05-11 18:59:33.026464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '897e5e96286d'
down_revision: Union[str, Sequence[str], None] = '7a1c4d3e9b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('location', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('meetings', sa.Column('end_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('meetings', sa.Column('timezone', sa.Integer(), nullable=True))
    op.alter_column('meetings', 'team_case_history_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('meetings', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('meetings', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('meetings', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meetings', 'team_case_history_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('meetings', 'timezone')
    op.drop_column('meetings', 'end_at')
    op.drop_column('meetings', 'start_at')
    op.drop_column('meetings', 'location')
    # ### end Alembic commands ###
