"""add uq to semesters table

Revision ID: 90551a1306a3
Revises: 
Create Date: 2026-05-08 19:37:26.853448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90551a1306a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_semesters_season_year', 'semesters', ['season', 'year'])
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teams', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('teams', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('uq_semesters_season_year', 'semesters', type_='unique')
    # ### end Alembic commands ###
