"""fix: add autoincrement to reference models

Revision ID: 9bf5bb861620
Revises: 
Create Date: 2026-04-10 13:28:43.538515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf5bb861620'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'case_difficulty_levels', ['id'])
    op.add_column('teams', sa.Column('description', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('notes', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'notes')
    op.drop_column('teams', 'description')
    op.drop_constraint(None, 'case_difficulty_levels', type_='unique')
    # ### end Alembic commands ###
