"""migration after adding some fields to integration models

Revision ID: ee9d810c2684
Revises: 9bf5bb861620
Create Date: 2026-05-03 20:25:16.272420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9d810c2684'
down_revision: Union[str, Sequence[str], None] = '9bf5bb861620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microsoft_oauth', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('microsoft_oauth', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('microsoft_oauth', 'microsoft_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('microsoft_oauth', 'last_refreshed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('microsoft_oauth', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microsoft_oauth', sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.alter_column('microsoft_oauth', 'last_refreshed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('microsoft_oauth', 'microsoft_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('microsoft_oauth', 'updated_at')
    op.drop_column('microsoft_oauth', 'id')
    # ### end Alembic commands ###
