"""add cascade delete to interviews

Revision ID: 02421cd290a6
Revises: 7b7f5c0d9e21
Create Date: 2026-06-08 23:39:21.074848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02421cd290a6'
down_revision: Union[str, Sequence[str], None] = '7b7f5c0d9e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curator_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_case_history_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_case_history_id'], ['team_case_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings_series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_case_history_id', sa.String(length=36), nullable=False),
    sa.Column('outlook_series_master_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_link', sa.String(), nullable=True),
    sa.Column('recurrence_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recurrence_range', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['team_case_history_id'], ['team_case_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('curator_meetings_attendance', sa.Column('is_present', sa.Boolean(), nullable=False))
    op.alter_column('curator_meetings_attendance', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('curator_meetings_attendance', 'meeting_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('curator_meetings_attendance', 'curator_assignment_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_foreign_key(None, 'curator_meetings_attendance', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key(None, 'curator_meetings_attendance', 'curator_assignments', ['curator_assignment_id'], ['id'])
    op.drop_constraint(op.f('interviews_case_id_fkey'), 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'bot_cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.add_column('meetings', sa.Column('meetings_series_id', sa.String(length=36), nullable=True))
    op.alter_column('meetings', 'event_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'meetings', 'meetings_series', ['meetings_series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.alter_column('meetings', 'event_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('meetings', 'meetings_series_id')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key(op.f('interviews_case_id_fkey'), 'interviews', 'bot_cases', ['case_id'], ['id'])
    op.drop_constraint(None, 'curator_meetings_attendance', type_='foreignkey')
    op.drop_constraint(None, 'curator_meetings_attendance', type_='foreignkey')
    op.alter_column('curator_meetings_attendance', 'curator_assignment_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('curator_meetings_attendance', 'meeting_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('curator_meetings_attendance', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('curator_meetings_attendance', 'is_present')
    op.drop_table('meetings_series')
    op.drop_table('curator_assignments')
    # ### end Alembic commands ###
