"""add restrict and casade on case models

Revision ID: 05d3bb9a27cf
Revises: 51850e0a9a34
Create Date: 2026-06-18 17:50:59.735559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d3bb9a27cf'
down_revision: Union[str, Sequence[str], None] = '51850e0a9a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('case_semesters_case_id_fkey'), 'case_semesters', type_='foreignkey')
    op.create_foreign_key('case_semesters_case_id_fkey', 'case_semesters', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('evaluation_form_case_id_fkey'), 'evaluation_form', type_='foreignkey')
    op.create_foreign_key('evaluation_form_case_id_fkey', 'evaluation_form', 'cases', ['case_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('team_members_team_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_members_team_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_team_id_fkey'), 'team_members', 'teams', ['team_id'], ['id'])
    op.drop_constraint('evaluation_form_case_id_fkey', 'evaluation_form', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_form_case_id_fkey'), 'evaluation_form', 'cases', ['case_id'], ['id'])
    op.drop_constraint('case_semesters_case_id_fkey', 'case_semesters', type_='foreignkey')
    op.create_foreign_key(op.f('case_semesters_case_id_fkey'), 'case_semesters', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###
