"""misc: add uq to EvaluationReactions model

Revision ID: 38d808ab6770
Revises: aae7498aaa81
Create Date: 2026-06-12 14:16:06.004817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d808ab6770'
down_revision: Union[str, Sequence[str], None] = 'aae7498aaa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_evaluation_form_id_user_id', 'evaluation_form_reactions', ['evaluation_form_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_evaluation_form_id_user_id', 'evaluation_form_reactions', type_='unique')
    # ### end Alembic commands ###
