"""add restrict to team_case_history fks

Revision ID: 51850e0a9a34
Revises: 38d808ab6770
Create Date: 2026-06-18 16:14:38.118134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51850e0a9a34'
down_revision: Union[str, Sequence[str], None] = '38d808ab6770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('team_case_history_team_id_fkey'), 'team_case_history', type_='foreignkey')
    op.drop_constraint(op.f('team_case_history_case_semesters_id_fkey'), 'team_case_history', type_='foreignkey')
    op.create_foreign_key(None, 'team_case_history', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'team_case_history', 'case_semesters', ['case_semesters_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_case_history', type_='foreignkey')
    op.drop_constraint(None, 'team_case_history', type_='foreignkey')
    op.create_foreign_key(op.f('team_case_history_case_semesters_id_fkey'), 'team_case_history', 'case_semesters', ['case_semesters_id'], ['id'])
    op.create_foreign_key(op.f('team_case_history_team_id_fkey'), 'team_case_history', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
