"""add CASCADE ondelete for commentsform's FK

Revision ID: afe434efbaed
Revises: 05d3bb9a27cf
Create Date: 2026-06-18 23:14:42.987284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe434efbaed'
down_revision: Union[str, Sequence[str], None] = '05d3bb9a27cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evaluation_form_case_id_fkey'), 'evaluation_form', type_='foreignkey')
    op.create_foreign_key('evaluation_form_case_id_fkey', 'evaluation_form', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('evaluation_form_comments_evaluation_form_id_fkey'), 'evaluation_form_comments', type_='foreignkey')
    op.create_foreign_key('evaluation_form_comments_evaluation_form_id_fkey', 'evaluation_form_comments', 'evaluation_form', ['evaluation_form_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('evaluation_form_reactions_evaluation_form_id_fkey'), 'evaluation_form_reactions', type_='foreignkey')
    op.create_foreign_key('evaluation_form_reactions_evaluation_form_id_fkey', 'evaluation_form_reactions', 'evaluation_form', ['evaluation_form_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('evaluation_form_reactions_evaluation_form_id_fkey', 'evaluation_form_reactions', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_form_reactions_evaluation_form_id_fkey'), 'evaluation_form_reactions', 'evaluation_form', ['evaluation_form_id'], ['id'])
    op.drop_constraint('evaluation_form_comments_evaluation_form_id_fkey', 'evaluation_form_comments', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_form_comments_evaluation_form_id_fkey'), 'evaluation_form_comments', 'evaluation_form', ['evaluation_form_id'], ['id'])
    op.drop_constraint('evaluation_form_case_id_fkey', 'evaluation_form', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_form_case_id_fkey'), 'evaluation_form', 'cases', ['case_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
