"""fix bot_cases id

Revision ID: bc56c0a3ffda
Revises: f9c1681e42cb
Create Date: 2026-05-26 15:07:17.958564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc56c0a3ffda'
down_revision: Union[str, Sequence[str], None] = 'f9c1681e42cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bot_cases', ['id'])
    op.create_unique_constraint(None, 'bot_mode', ['id'])
    op.create_unique_constraint(None, 'interviews', ['id'])
    op.drop_constraint(op.f('interviews_case_id_fkey'), 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'bot_cases', ['case_id'], ['id'])
    op.create_unique_constraint(None, 'recruitment_curators', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruitment_curators', type_='unique')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key(op.f('interviews_case_id_fkey'), 'interviews', 'cases', ['case_id'], ['id'])
    op.drop_constraint(None, 'interviews', type_='unique')
    op.drop_constraint(None, 'bot_mode', type_='unique')
    op.drop_constraint(None, 'bot_cases', type_='unique')
    # ### end Alembic commands ###
