"""add bot tables

Revision ID: f9c1681e42cb
Revises: c82ca541bacf
Create Date: 2026-05-25 21:36:17.987964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c1681e42cb'
down_revision: Union[str, Sequence[str], None] = 'c82ca541bacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recruitment_curators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bot_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('meeting_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'case_difficulty_levels', ['id'])
    op.create_unique_constraint(None, 'cases', ['id'])
    op.create_unique_constraint(None, 'grades', ['id'])
    op.create_unique_constraint(None, 'students', ['id'])
    op.create_unique_constraint(None, 'team_case_history', ['id'])
    op.create_unique_constraint(None, 'teams', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'team_case_history', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'grades', type_='unique')
    op.drop_constraint(None, 'cases', type_='unique')
    op.drop_constraint(None, 'case_difficulty_levels', type_='unique')
    op.drop_table('meeting_tasks')
    op.drop_table('interviews')
    op.drop_table('bot_cases')
    op.drop_table('recruitment_curators')
    op.drop_table('bot_mode')
    # ### end Alembic commands ###
